### ISSUE TITLE
Most mounted disk images look empty

### ISSUE THREAD

**Issue by lifepillar** [ksherlock/profuse#2]
I am having little luck mounting disk images. I have tried with several ones, standard ProDOS or DOS3.3 formatted, but in nearly all cases they are mounted as an empty volume. This is what I do:
1. Create an empty directory in my home directory;
2. Mount a disk image using `profuse`, using the above directory as the mount point.

I have tried with different combinations of the options.  Since sometimes I do see an image mounted correctly, I guess that I am either using the wrong options or an unsupported format.

I attach an archive with a few examples: `dusthead_v1.1.po` and `ROGUE.PO` can be mounted correctly (without passing any additional options), but the remaining disk images are not. I am not getting any errors from `profuse`.

Using the current master and FUSE for OS X 2.8.3.
[disk_images.zip](https://github.com/ksherlock/profuse/files/421990/disk_images.zip)

**Comment by ksherlock** [comment]
On OS X, it automatically creates a folder in /Volumes and mounts it in there so you don't need to worry about creating a directory for a mount point. Diags.do isn't a ProDOS disk.  PRODOS copy.po looks like it's in DOS order (change the extension to .do or use the --format=do flag). The others mount fine for me.

Kelvin

**Comment by lifepillar** [comment]
Ah ok, now it's clear. Using the same directory for my all tests was not a good idea: I was probably leaving behind not cleanly unmounted volumes. Thanks!
